### ISSUE TITLE
Upgrade 'org.jetbrains.kotlin.jvm' plugin version for kotlin project template

### ISSUE THREAD

**Issue by Gasloff** [Haulmont/jmix-templates#54]
From current version: 1.4.32 to new version: 1.5.10

With current version compileKotlin task fails on Unix and IDEA 2021.3 (Kotlin Idea plugin version 213-1.5.10) JDK 11+

**Comment by Gasloff** [comment]
QA notes: Check that project with kotlin.jvm plugin 1.5.10 compiles on all supported IDEs (2021.1, 2021.2, 2021.3)

**Comment by konyashkina** [comment]
Tested with Java 17 
- [x] 211
- [x] 212
- [x] 213  
Some errors appear in Idea log while the application is running:
- Caused by: java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @2db7a79b)
- Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @2db7a79b)
- Parameter 'event' is never used (warning)

With Java 11:  only "Parameter 'event' is never used" warning appears.

**Comment by konyashkina** [comment]
New issue opened about errors 
https://github.com/Haulmont/jmix-templates/issues/56
